### ISSUE TITLE
Acceso a la DB desde poolConexio.java

### ISSUE THREAD

**Issue by TorreManias** [soymegh/UCASH#2]
El pool de conexión todavía usa el link de conexión de la base de datos del proyecto del grupo de @BrunoMazzocchi 

Es necesario que modifiquen esta conexión antes que el resto pueda hacer un merge de sus ramas con el main para que no existan conflictos a futuro con esta clase (porque todos lo estamos modificando para poder trabajar).

**Comment by TorreManias** [comment]
@soymegh @jxareas Pueden revisar?

**Comment by soymegh** [comment]
Ok, voy a revisarlo 

Seria Buenos que te hagas un pull request con ese cambio exclusivamente para aceptarlo hoy mismo, solo haciendo una actualizacion a lo que seria el pool de conexión

**Comment by BrunoMazzocchi** [comment]
Lleva 5 días mi pull request dónde ya hice el cambio en el pool de conexión a dbucash.

**Comment by soymegh** [comment]
Ya lo he aceptado, podrían verificar si esta funcional

**Comment by TorreManias** [comment]
Voy a ver

**Comment by BrunoMazzocchi** [comment]
Pool de conexion ya esta usando /dbucash.
